name: Downstream Workflow

on:
  workflow_run:
    workflows: [First Workflow]
    types: [completed]

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        type: choice
        required: true
        options:
          - prod
          - dev
      tag:
        description: 'Release tag'
        type: string
        required: true
# on:
#   workflow_dispatch:
#     inputs:
#       message:
#         type: string
#       something:
#         type: string
env:
  ENV: ${‎{ github.event_name == 'workflow_dispatch' && prod || dev }}

jobs:
  retrieve-and-use-cache:
    runs-on: ubuntu-latest
    environment: ${env.ENV}
    steps:
      - name: Assign var
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
          if [ "${‎{ github.event_name }‎}" = "workflow_run" ]; then
            echo "TAG=${‎{ github.event.head_branch }‎}" >> $GITHUB_ENV
          fi;
          if [ "${‎{ github.event_name }‎}" = "workflow_dispatch" ]; then
            echo "TAG=${‎{ inputs.tag }‎}" >> $GITHUB_ENV
          fi;
          
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://b2f9-124-233-1-146.ngrok-free.app/deploy'
          method: 'POST'
          username: "admin"
          password: "admin"
          customHeaders: '{"Content-Type": "multipart/form-data"}'
          data: '{"tag": "${{ github.repository }}/${{env.TAG}}"}'
          file: "./.env"
    

# jobs:
#   use-data:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Retrieve cache
#         run: |
#           echo ${{inputs.message}}
#           echo ${{inputs.something}}
        
