name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '发布的环境'
        type: choice
        required: true
        options:
          - prod
          - dev
      tags:
        description: '发布版本tag'
        type: string
        required: true
      perform_deploy:
        required: true
        type: boolean
  push:
    branches:
      - main
  
env:
  PORT: ${{vars.PORT}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run script
        run: |
          echo "PORT=${{vars.PORT}}" >> .env
          echo ${PORT}
          echo ${{inputs.tags}}
          cat .env
      - name: Run script
        if: ${{ inputs.perform_deploy }}
        run: |
          echo ${{ inputs.environment }}
          echo ${{inputs.tags}}
           
      
          
        
      
          
      
