name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '发布的环境'
        type: choice
        required: true
        options:
          - prod
          - dev
      tags:
        description: '发布版本tag'
        type: string
        required: true
  push:
    branches:
      - main
  
env:
  PORT: ${{vars.PORT}}
  PRODUCTION: ${{ inputs.environment == 'prod' && true || false }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ PRODUCTION && 'prod' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run script
        if: ${{ PRODUCTION == false }}
        run: |
          echo "PORT=${{vars.PORT}}" >> .env
          echo ${PORT}
          echo ${{inputs.tags}}
          echo ${{PRODUCTION && 'true' || 'false'}}
          cat .env
      - name: Build script
        if: ${{ PRODUCTION == true }}
        run: |
          echo ${{ inputs.environment }}
          echo ${{inputs.tags}}
          echo ${{PRODUCTION && 'true' || 'false'}}
          
           
      
          
        
      
          
      
