name: 12 - Run Workflow

on:
  workflow_run:
    workflows: ["12 - Workflow Tester"]
    types: [completed]


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "First workflow was a failure"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show workflow_run
        env:
          WORKFLOW_CONTEXT: ${{ toJSON(github.event.workflow_run) }}
        run: |
          echo ${{ github.event.workflow_run }}
          echo $WORKFLOW_CONTEXT
