name: Deployment

on:
  push:
    branches:
      - main

env:
  PORT: ${{vars.PORT}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          echo "PORT=${{vars.PORT}}" >> .env
          echo ${PORT}
          cat .env
