name: Downstream Workflow

on:
  workflow_run:
    workflows: [First Workflow]
    types: [completed]

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        type: choice
        required: true
        options:
          - prod
          - dev
      tag:
        description: 'Release tag'
        type: string
        required: true
# on:
#   workflow_dispatch:
#     inputs:
#       message:
#         type: string
#       something:
#         type: string
env:
  ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || 'dev' }}
  EVENT: ${{ toJSON(github.event) }}
jobs:
  retrieve-and-use-cache:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Set var name
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi;
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi;
      - name: Set env file
        run: |
          echo "# Autogenerated .env file" > .env
          echo ${{env.TAG}}
          timestamp=$(date +%s)
          echo "timestamp=${timestamp}" >> $GITHUB_ENV
          md5_value=$(echo -n "your string here${timestamp}" | md5sum | awk '{print $1}')
          echo "sign=${md5_value}" >> $GITHUB_ENV
      # - name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'https://b2f9-124-233-1-146.ngrok-free.app/deploy'
      #     method: 'POST'
      #     username: "admin"
      #     password: "admin"
      #     customHeaders: '{"Content-Type": "multipart/form-data"}'
      #     data: '{"tag": "${{ github.repository }}/${{env.TAG}}"}'
      #     files: '{"file": ".env"}'
          
    

# jobs:
#   use-data:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Retrieve cache
#         run: |
#           echo ${{inputs.message}}
#           echo ${{inputs.something}}
        
