name: Second Workflow

on:
  repository_dispatch:
    types: ['second-workflow']

jobs:
  second-job:
    runs-on: ubuntu-latest

    steps:
      # 执行第二个工作流的任务
      - name: Print Parameters
        run: |
          echo ${{ github.event.client_payload }}
        
