name: Downstream Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed
# on:
#   workflow_dispatch:
#     inputs:
#       message:
#         type: string
#       something:
#         type: string

env:
  workflow: ${{ toJSON(github.event.workflow_run) }}

jobs:
  retrieve-and-use-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve cache
      uses: actions/cache@v3
      with:
        path: data-directory
        key: data-${{ github.event.workflow_run.id }}

    - name: Read cached data
      run: |
        cat data-directory/data.txt >> $GITHUB_ENV

# jobs:
#   use-data:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Retrieve cache
#         run: |
#           echo ${{inputs.message}}
#           echo ${{inputs.something}}
        
