name: Downstream Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
      something:
        type: string

jobs:
  use-data:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cache
        run: |
          echo ${{inputs.message}}
          echo ${{inputs.something}}
        
