name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '发布的环境'
        type: choice
        required: true
        options:
          - prod
          - dev
      tags:
        description: '发布版本tag'
        type: string
        required: true
  push:
    branches:
      - main
  
env:
  PORT: ${{vars.PORT}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
       - name: Executing remote ssh commands
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.PROXY_HOST }}
          username: ${{ secrets.PROXY_USERNAME }}
          password: ${{ secrets.PROXY_KEY }}
          script: |
            whoami
            ls -al
          
           
      
          
        
      
          
      
