name: Second Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: false

jobs:
  second-job:
    runs-on: ubuntu-latest

    steps:
      # 执行第二个工作流的任务
      - name: Print Parameters
        run: |
          echo ${{ inputs.param1 }}
          echo ${{ inputs.param2 }}
        
