name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          echo "PORT=${{vars.PORT}}" >> .env
          cat .env
