name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        options:
          - prod
          - dev
      tags:
        description: 'Environment to run tests against'
        type: string
        required: true
      perform_deploy:
        required: true
        type: boolean
  push:
    branches:
      - main
  
env:
  PORT: ${{vars.PORT}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          echo "PORT=${{vars.PORT}}" >> .env
          echo ${PORT}
          echo ${{inputs.tags}}
          cat .env
          
      
