name: Downstream Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
      something:
        type: string

jobs:
  retrieve-and-use-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve cache
      uses: actions/cache@v3
      with:
        path: data-directory
        key: data-${{ github.event.workflow_run.id }}

    - name: Use cached data
      run: |
        cat data-directory/data.txt

# jobs:
#   use-data:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Retrieve cache
#         run: |
#           echo ${{inputs.message}}
#           echo ${{inputs.something}}
        
