name: 12 - Workflow Tester

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache data
        uses: actions/cache@v3
        with:
          path: path/to/data
          key: data-${{ github.run_id }}
