name: 12 - Workflow Tester

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # 执行第一个工作流的任务
  
      - name: Trigger Second Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: second-workflow
          client-payload: '{"mydata": "bbbb" }'
