name: 12 - Workflow Tester

on:
  workflow_call:
    outputs:
      output1:
        description: "The first job output"
        value: ${{ jobs.test.outputs.output1 }}
      output2:
        description: "The first job output"
        value: ${{ jobs.test.outputs.output2 }}
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs }}
      output2: ${{ steps.step2.outputs }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
