name: 12 - Workflow Tester

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Downstream Workflow
          repo: ${{ github.repository }}
          inputs: '{ "message": "blah blah", "something": false }'
          token: ${{secrets.TOKEN}}
