name: First Workflow

on:
  push:
    branches:
      release-**

permissions: read-all

env:
  EVENT: ${{ toJSON(github.event) }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_output.outputs.value }}
    steps:
    - name: Generate data
      run: |
        mkdir -p data-directory
        echo "PORT=8000" > data-directory/data.txt

    - name: Set tag
      run: |
        echo "TAG=${GITHUB_REF#refs/heads/}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - id: set_output
      run: |
        echo "value=123" >> $GITHUB_OUTPUT
        
    - name: Use GitHub Context
      run: |
        echo "The branch name is ${GITHUB_REF#refs/heads/}"
        echo ${{env.TAG}}
      env:
        GITHUB_REF: ${{ github.ref }}

  use_setup:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Out value
        run: |
          echo "The output from 'setup' job is ${{ needs.setup.outputs.tag }}"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment: dev
#     steps:
#       - name: Invoke workflow in another repo with inputs
#         uses: benc-uk/workflow-dispatch@v1
#         with:
#           workflow: Downstream Workflow
#           repo: ${{ github.repository }}
#           inputs: '{ "message": "blah blah", "something": false }'
#           token: ${{secrets.TOKEN}}
