name: 12 - Workflow Tester

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      # 执行第一个工作流的任务

      - name: Set Output
        id: output
        run: echo "value=hello" >> $GITHUB_OUTPUT
